### ISSUE TITLE
The request header REQUEST_URI contains PII or secrets that should be stripped via filter_parameters

### ISSUE THREAD

**Issue by jbockler** [appsignal/appsignal-ruby#1038]
## Describe the bug

Eventhough a GET parameter is configured in filter_parameters due to it containing PII or a secret API token for example, the REQUEST_URI request header is not getting filtered and is leaking this information to Appsignal.

Of course i could simply remove the REQUEST_URI from `request_headers` config, but it is not stated in the docs anywhere
and is easy to oversee. On the other hand from description of the `filter_parameters` i would have assumed that this will get filtered too.

## To Reproduce

- Using AppSignal for Ruby gem version 3.5.5
- In my app using rails 7.1.2
- With this code:
  ```
  # appsignal.yml:
  default: &defaults
    push_api_key: "foo"
    name: "MyApplication"
    filter_parameters: ["api_token"]

  development:
    <<: *defaults
    active: true

  production:
    <<: *defaults
    active: true
  ```
- Doing Request to a route and add `?api_token=staysecret` and the request should fail
- I see in AppSignal in the "Parameters" section the parameters correctly as "[FILTERED]"
- In the "Environment" section i see the whole REQUEST_URI with `/sample?api_token=staysecret`
