### ISSUE TITLE
Unable to use ENV var for API key in multiple environments

### ISSUE THREAD

**Issue by erkattak** [appsignal/appsignal-ruby#3]
https://github.com/appsignal/appsignal/blob/master/lib/appsignal/config.rb#L84-L92

``` ruby
    def used_unique_api_keys
      keys = configurations.each_value.map { |config| config[:api_key] }.compact
      if keys.uniq.count < keys.count
        carefully_log_error('Duplicate API keys found in appsignal.yml')
        false
      else
        true
      end
    end
```

This does not take into account someone using the following config file

``` yaml

---
development:
  active: false
production:
  api_key: "<%= ENV['APPSIGNAL_API_KEY'] %>"
  active: true
  ignore_exceptions:
    - ActiveRecord::RecordNotFound
    - ActionController::RoutingError
staging:
  api_key: "<%= ENV['APPSIGNAL_API_KEY'] %>"
  active: true
  ignore_exceptions:
    - ActiveRecord::RecordNotFound
    - ActionController::RoutingError
```
