### ISSUE TITLE
Set environment from `appsignal.yml` file.

### ISSUE THREAD

**Issue by matsimitsu** [appsignal/appsignal-ruby#493]
In our Elixir integration you can set the environment in the config file. This is also the reason that it's documented here https://docs.appsignal.com/ruby/configuration/options.html#option-env (it uses the same source file).

However in Ruby you can only override the reporting environment from ENV vars, which is not very convenient when using Capistrano for deploys.

A solution would be to set a root key in the config with the reporting env:

```yaml
env: "staging"

default: &defaults
  # Your push api key, it is possible to set this dynamically using ERB:
  push_api_key: "<%= ENV['APPSIGNAL_PUSH_API_KEY'] %>"

  # Your app's name
  name: "MyApp"

development:
  <<: *defaults
  active: false

staging:
  <<: *defaults
  active: true

production:
  <<: *defaults
  active: true
```

IC: https://app.intercom.io/a/apps/yzor8gyw/inbox/inbox/14894/conversations/21294080501
